name: 'setup-node'
description: 'setup node'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
  disabled-cache:
    description: 'Disable cache'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Get Node.js version from volta
      if: ${{ !inputs.node-version }}
      shell: bash
      run: echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: ${{ inputs.node-version || env.NODE_VERSION }}

    - name: Cache node modules
      if: ${{ inputs.disabled-cache != 'true' }}
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}