name: 'setup-node'
description: 'setup node'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
  npm-version:
    description: 'npm version'
    required: false
  disabled-cache:
    description: 'Disable cache'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Get Node.js version from volta
      if: ${{ !inputs.node-version }}
      shell: bash
      run: echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_ENV

    - name: Get npm version from volta
      if: ${{ !inputs.npm-version }}
      shell: bash
      run: echo "NPM_VERSION=$(jq -r .volta.npm package.json)" >> $GITHUB_ENV

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: ${{ inputs.node-version || env.NODE_VERSION }}

    - name: Setup npm version
      if: ${{ inputs.npm-version || env.NPM_VERSION }}
      shell: bash
      run: npm install -g npm@${{ inputs.npm-version || env.NPM_VERSION }}

    - name: Cache node modules
      if: ${{ inputs.disabled-cache != 'true' }}
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: '**/node_modules'
        key: npm-${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}